---
jobs:
  image:
    name: Image
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-26.04
    steps:
      # Set up Docker
      # https://github.com/docker/setup-docker-action
      - name: Set up Docker
        uses: docker/setup-docker-action@2bf61fb9464cc67f0cbdeabed6aa0380accd1c70 # v5.5.0
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      # Set up Docker Compose
      # https://github.com/docker/setup-compose-action
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@54042514f505b273907334ae2b9cdbb9a0213c1a # v2.4.0
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # Build and start image
      - name: Build and start image
        run: |
          docker compose --progress plain up \
            --build \
            --attach=${{ inputs.test-container-name }} \
            --exit-code-from=${{ inputs.test-container-name }}
        working-directory: ${{ inputs.test-directory }}
name: Test
on:
  workflow_call:
    inputs:
      app-container-name:
        default: "app"
        description: "The name of the container running the app being tested"
        required: false
        type: string
      test-container-name:
        default: "connection_test"
        description: "The name of the container running the tests (connection, expected output, etc.)"
        required: false
        type: string
      test-directory:
        default: "tests"
        description: "The directory containing your test docker-compose.yaml file"
        required: false
        type: string
permissions:
  contents: read
  pull-requests: write
