---
jobs:
  image:
    name: Image
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      # Set up Docker
      # https://github.com/docker/setup-docker-action
      - name: Set up Docker
        uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v5.1.0
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      # Set up Docker Compose
      # https://github.com/docker/setup-compose-action
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@8cccb8c14b6500aaffebff1aa49c502c34d2e5e6 # v2.1.0
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Build and start image
      - name: Build and start image
        run: |
          docker compose --progress plain up \
            --build \
            --attach=${{ inputs.test-container-name }} \
            --exit-code-from=${{ inputs.test-container-name }}
        working-directory: ${{ inputs.test-directory }}
name: Test
on:
  workflow_call:
    inputs:
      app-container-name:
        default: "app"
        description: "The name of the container running the app being tested"
        required: false
        type: string
      test-container-name:
        default: "connection_test"
        description: "The name of the container running the tests (connection, expected output, etc.)"
        required: false
        type: string
      test-directory:
        default: "tests"
        description: "The directory containing your test docker-compose.yaml file"
        required: false
        type: string
permissions:
  contents: read
  pull-requests: write
